name: traj-alignment
channels:
  - conda-forge
dependencies:
  - python=3.12

  # Jupyter stack
  - ipython
  - ipykernel
  - jupyterlab
  - ipywidgets
  - jupytext
  - pandoc

  # Scientific Python
  - numpy >=2,<2.3.0
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - tqdm

  # Dev / workflow
  - pre-commit
  - pyyaml
  - pip

  # Interop
  - rpy2

  # Optional (only if needed)
  - nodejs
