name: r4.4_env
channels:
  - conda-forge
dependencies:
  - bioconductor-complexheatmap
  - bioconductor-scater
  - bioconductor-scuttle
  - bioconductor-singlecellexperiment
  - bioconductor-slingshot
  - bioconductor-tradeseq
  - bioconductor-trajectoryutils
  - r-base=4.4
  - r-cowplot
  - r-dplyr
  - r-emmeans
  - r-ggbeeswarm
  - r-ggplot2
  - r-knitr
  - r-lme4
  - r-lmertest
  - r-magrittr
  - r-markdown
  - r-patchwork
  - r-purrr
  - r-qs
  - r-tidyverse
  - r-tinytex
  - r-viridis
  - bioconductor-delayedmatrixstats
  - r-ggridges
  - r-pacman
  - bioconductor-tscan
  - bioconductor-scran
  - r-devtools
  - r-ggnewscale
  - r-coin
  - r-effects
  - bioconductor-biostrings
  - r-ggdendro
  - r-ggextra
  - bioconductor-condiments
  - r-seurat
  - r-harmony
  - btop
  - r-brms
  - r-cmdstanr
  - gcc
  - gxx
  - tbb
  - tbb-devel
  - r-rcppparallel
  - r-stanheaders
  - r-ggeffects
  - r-tidytext
  - r-mertools
  - ncbi-datasets-cli
  - r-vegan
  - r-snakecase
prefix: /projects/canderson2@xsede.org/software/anaconda/envs/r4.4_env
