cell_metadata_filter = "all,-execution,-papermill,-trusted"
notebook_metadata_filter = "-jupytext.text_representation.jupytext_version"

# ipynb in .  <->  py in ./py/
formats = "ipynb,py//py:percent"
